---
title: "20210727 Classifying - KNN (cross-validation)"
author: "cheungngo"
date: "27 July 2021"
output: html_document
---

### Preparing the libraries and data and others

```{r, message=FALSE, warning=FALSE}
library(mclust)
library(tidyverse)
library(mlr)
```

```{r}
data("diabetes")
# The data set contains three measurements made on 145 non-obese adult patients classified into three groups.
```

```{r}
dm = diabetes
dm_tib = as_tibble(diabetes)
```

```{r}
task_dm = makeClassifTask(data = dm_tib,
                          target = "class")
learner_dm = makeLearner("classif.knn",
                         par.vals = list("k" = 3))
```

### Holdout cross-validation

```{r}
# resample specifications

holdout = makeResampleDesc(method = "Holdout",
                           split = 2/3,
                           stratify = T) # same proportion of each class of patient in each set

holdout
```

```{r}
# arguments please refer to ?makeResampleDesc -> Arguments -> predict
```

```{r}
# resample

holdoutCV = resample(learner = learner_dm,
                     task = task_dm,
                     resampling = holdout,
                     measures = list(mmce,acc))
```

```{r}
# confusion matrix

calculateConfusionMatrix(holdoutCV$pred, 
                         relative = T) # to show to proportion (relative confusion matrix)
```


### k-fold cross-validation

```{r, message = FALSE}
kfold = makeResampleDesc(method = "RepCV",
                         folds = 10,
                         reps = 50, # splitting repeated for 50 times
                         stratify = T)
kfoldCV = resample(learner = learner_dm,
                   task = task_dm,
                   resampling = kfold,
                   measures = list(mmce,acc))
```

```{r}
kfoldCV$aggr # average performance
```

```{r}
calculateConfusionMatrix(kfoldCV$pred, relative = T)
```

